### PR TITLE
 add mongodb update bugbounty-list.json

### PR DESCRIPTION
**Pull request by ismailtasdelen**
<b>MongoDB : </b>
```
      {
         "name":"MongoDB",
         "url":"https://www.mongodb.com/security",
         "bounty":false,
         "domains":[
            "mongodb.com"
         ]
      },
```

### CODE REVIEW

**Comment by bauthard** [comment]
@ismailtasdelen We are also sending the invites to access [Chaos platform](https://chaos.projectdiscovery.io) API to all the contributors, if you are interested please fill the following [google form](https://forms.gle/Lpc9Lnkna3g96pHB6).

**Comment by ismailtasdelen** [comment]
Hi @bauthard,

I applied before, but I did not get an answer. I have applied again now. 

Thanks @bauthard 

Regards,
@ismailtasdelen

**Comment by bauthard** [comment]
We sent an invite to you @ismailtasdelen.

**Comment by ismailtasdelen** [comment]
Thanks @bauthard 👍

**Pull request merged**
