### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GHAJW**
making sure I got the CI/CD pipe laid to aid the rabbitholed

### CODE REVIEW

**Comment by GHAJW** [comment]
seems to be working out okay.  wait till lunch, check with peers, dear!

**Comment by GHAJW** [comment]
ok

**Comment by GHAJW** [comment]
oopsies

**Review by GHAJW — COMMENTED** [review]
ok
download

**Comment by GHAJW** [comment]
do it

**Comment by bauthard** [comment]
Hey @GHAJW, 

Please do not submit irrelevant PR and updating it for no reason.

**Pull request closed without merging**
