### PR TITLE
fix(ValidateFQDN): Modifying ValidateFQDN to only look at ICANN domains

### PR DESCRIPTION
**Pull request by MattSilvaa**
This PR addresses https://github.com/projectdiscovery/public-bugbounty-programs/issues/532

To make `ngrok.io` not return false, we have to ignore all private domains in the PSL and only look at ICANN ones.

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
@MattSilvaa this results into a new issue with other domains.

```console
validate-domains $./validate-domains 
validate-domains $bat invalid_domains.txt 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: invalid_domains.txt
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ clientondersteuning.co.nl
   2   │ mailfoogae.appspot.com
   3   │ d2evh2mef3r450.cloudfront.net
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by MattSilvaa** [comment]
> @MattSilvaa this results into a new issue with other domains.
> 
> ```
> validate-domains $./validate-domains 
> validate-domains $bat invalid_domains.txt 
> ───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>        │ File: invalid_domains.txt
> ───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>    1   │ clientondersteuning.co.nl
>    2   │ mailfoogae.appspot.com
>    3   │ d2evh2mef3r450.cloudfront.net
> ───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> ```

I think the right move is to update our publicsuffix package to `github.com/weppos/publicsuffix-go/publicsuffix` so that it's pulling the latest PSL and then to also update `chaos-bugbounty-list` to remove all the incorrect domain names for `ngrok`... it should only be `ngrok.com`. This is the result of `validate-domains` using the updated publicsuffix package while not ignoring private tlds.

```
ngrok.io
ngrok-free.app
ngrok-free.dev
ngrok.app
ngrok.dev
```
As you can see, it outlines the bug which is that we are using the wrong domain values for ngrok. I will push up the changes. Looking forward to hear your thoughts.

**Comment by ehsandeep** [comment]
@MattSilvaa, thanks for the update, I've updated `publicsuffix-go` to the latest commit and still see the same issue, removing domains from the list is not a solution as a) we need to keep those domains 2) we can have more domains in future with same TLD's.

**Review by tarunKoyalwar — COMMENTED** [review]
@MattSilvaa  thanks for PR but we currently only rely on publicsuffix for domain validation which is not the case with domains like http://ngrok.io or http://ai . i have created a issue to furthur improve support for TLDs [here](https://github.com/projectdiscovery/public-bugbounty-programs/issues/536)

we can close this PR and if you are interested , you can pick that issue

**Pull request closed without merging**
