### PR TITLE
scope.json

### PR DESCRIPTION
**Pull request by ticzox**

### CODE REVIEW

**Comment by bauthard** [comment]
Thank you for the PR, I've updated this here https://github.com/projectdiscovery/public-bugbounty-programs/commit/1b0a46d5216cf3a8c3ea7bdbe728315080aff8f6 @ticzox, make sure you do `git pull` as you are on an older version of this project.

**Comment by ticzox** [comment]
Hello  @bauthard ,
can you please elaborate this `make sure you do git pull as you are on an older version of this project.`  i didn't get it

**Comment by bauthard** [comment]
We have updated the `scope.json` file to `chaos-bugbounty-list.json` in our Github project, but you are still on `scope.json` means you are using an outdated version of the project, `git pull` or cloning the project again will update your files to latest one @ticzox

**Comment by ticzox** [comment]
I have updated the file name from `scope.json` to `chaos-bugbounty-list.json` @bauthard

**Comment by bauthard** [comment]
No action needed here @ticzox, I've already added the requested domain the `chaos-bugbounty-list.json` :)

**Comment by ticzox** [comment]
okay thanks @bauthard :)

**Pull request closed without merging**
