### PR TITLE
add a new program to the list

### PR DESCRIPTION
**Pull request by randomboy77**
first pull request so don't bully me;)
also there are like 10+ more domains but i'm too busy to put all of them
hope it hels and good luck on your journey ahead

### CODE REVIEW

**Comment by ehsandeep** [comment]
@randomboy77 I updated the domains as you need to submit root domain name, also I don't see any reference of domains you listed on the given URL, can you confirm from where you pulling these domain names?

**Comment by randomboy77** [comment]
hello there,
the domains are listed on the target scope of the program,

**Comment by ehsandeep** [comment]
thank you @randomboy77, but we can only add hosts which is publicly listed or available to view.

**Comment by ehsandeep** [comment]
Closing this PR, as the information is not available publicly.

**Pull request closed without merging**
