### PR TITLE
Update Swisscom bug bounty program details

### PR DESCRIPTION
**Pull request by antoinet**
Removed the domains as they are outdated. This repository also does not account for exclusions. For details, refer to https://github.com/swisscom/bugbounty/tree/main/scope

### CODE REVIEW

**Comment by antoinet** [comment]
sir, any updates?

**Review by ehsandeep — APPROVED** [review]

**Comment by meme-lord** [comment]
I'm confused, why is the list of domains outdated? Most if not all those domains are still contained in https://github.com/swisscom/bugbounty/blob/main/scope/inscope.txt

**Comment by antoinet** [comment]
Swisscom operates an open-scope program, and the list of assets is rather complex. The scope is provided in two lists, one to [include](https://github.com/swisscom/bugbounty/blob/main/scope/inscope.txt) and another to [exclude](https://github.com/swisscom/bugbounty/blob/main/scope/outofscope.txt) assets. You can refer to this [illustration](https://twitter.com/ant0inet/status/1604432698113773571) for an example of why this is needed. Also, the scope changes many times a year. Therefore the list provided in the PD repository does not reflect an accurate state of our scope, resulting in participants actually testing out-of-scope assets, which puts them at risk since this represents an offense according to the Swiss penal code. I hope this helps clarify the situation.

**Comment by antoinet** [comment]
I think it's dangerous to assume that "someone" will always make sure the scope is kept up to date. I think it's preferable to avoid any risks.

**Pull request merged**
