### PR TITLE
eTLD validation support in ValidateFQDN

### PR DESCRIPTION
**Pull request by MattSilvaa**
Draft PR for https://github.com/projectdiscovery/public-bugbounty-programs/issues/536 and https://github.com/projectdiscovery/public-bugbounty-programs/issues/532

### CODE REVIEW

**Comment by MattSilvaa** [comment]
@tarunKoyalwar @ehsandeep I created this draft PR per the new issue. Would something like this be more appropriate?

**Review by ehsandeep — APPROVED** [review]

**Review by tarunKoyalwar — APPROVED** [review]

**Comment by ehsandeep** [comment]
Thank you @MattSilvaa, for fixing this one!

**Comment by olearycrew** [comment]
Thanks for this @MattSilvaa - you can check out https://defcon.projectdiscovery.io/countdown as this issue is part of this program 😄

**Comment by MattSilvaa** [comment]
> Thanks for this @MattSilvaa - you can check out https://defcon.projectdiscovery.io/countdown as this issue is part of this program smile

Thanks for sharing! I will sign up and look forward to contributing more 😄

**Pull request merged**
